version: "3.3"
services:
  cryptostore:
    image: cryptostore:latest
    depends_on:
      - quest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - EXCHANGE=BITSTAMP
      - CHANNELS=trades,l2_book
      - SYMBOLS=BTC-USD,ETH-USD,ETH-BTC
      - SNAPSHOT_ONLY=True
      - MAX_DEPTH=20
      - BACKEND=QUEST
      - HOST=quest
      - PORT=9009
  quest:
    image: questdb/questdb
    environment:
      - QDB_LOG_W_STDOUT_LEVEL=ERROR
      - QDB_PG_READONLY_USER_ENABLED=true
    ports:
      - 9009:9009
      - 8812:8812
      - 9000:9000
    volumes:
      - market-data:/var/lib/questdb
  # redis:
  #   image: redis:alpine
  #   command: redis-server --appendonly yes --appendfsync everysec --save 60 1000 --maxmemory 1gb --maxmemory-policy allkeys-lru
  #   ports:
  #     - 6379:6379
  #   volumes:
  #     - market-data:/data

  # redis-commander:
  #   image: plainid/redis-commander:latest-master
  #   environment:
  #     - REDIS_HOSTS=redis
  #   ports:
  #     - 8081:8081

volumes:
  market-data:

